- hosts: localhost
  gather_facts: false
  connection: local

  vars_prompt:
    - name: stack_name
      prompt: What's the name of the stack to be launched?
      when: stack_name is undefined

  pre_tasks:
    - include_vars: "../stacks/{{ stack_name }}.yml"
      tags: [always]

  roles:
    - role: vpc
      tags: [always]

